# Site settings
title:            Virgo
description:      A Jekyll template
url:              "http://yourdomain.com"
baseurl:          "" # the subpath of your site, e.g. /blog/

google_analytics: ""

# Author settings
author:           Alex Kleinubing
email:            alex.kleinubing@gmail.com
social:
  facebook:       /jekyllrb
  instagram:      jekyllrb
  linkedin:       jekyllrb
  github:         jekyll
  twitter:        jekyllrb

avatar:           ""

# Defaults
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      author: "Alex Kleinubing"



# General options
comments:         true
disqus-shortname: jekylltemplates

# Build settings
permalink:        ":categories/:title"
paginate:         10
paginate_path:    "/page/:num/"
source:           _source
destination:      _site
highlighter:      pygments
markdown:         kramdown
kramdown:
  input:          GFM #Github markdown style

repo:             http://github.com/nandomoreirame/nandomoreirame.github.io

exclude:          ["node_modules", ".sass-cache"]